version: '3.8'

services:
  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3,dynamodb
      - DEBUG=1
      - AWS_DEFAULT_REGION=ap-southeast-1
    volumes:
      - localstack_data:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock
      - ./infrastructure/localstack-init.sh:/etc/localstack/init/ready.d/init.sh

volumes:
  localstack_data:
    driver: local
