version = 0.1

[default.deploy.parameters]
stack_name = "ai-document-assistant"
resolve_s3 = true
s3_prefix = "ai-document-assistant"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"dev\" AllowedOrigins=\"*\""
image_repositories = []